version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.11 #

    # directory where steps are run. Path must conform to the Go Workspace requirements
    working_directory: /go/src/github.com/logic-building/functional-go/

    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: go test -v ./... # Run the tests
      - run:
          go test $(go list ./fp*) -coverprofile coverage.out
          go tool cover -func coverage.out

      - run:
          go test $(go list ./set*) -coverprofile coverage.out
          go tool cover -func coverage.out
          
      - run: go test -v -race ./...
      - run: go vet ./...
